Repository rollbar/rollbar-ios, pull requests merged in 2020-08, with the labels that each got.

#312 Ref#285 multiproject workspace
  CHANGELOG.md
  Demos/macosAppObjC/macosAppObjC.xcodeproj/project.pbxproj
  Demos/macosAppObjC/macosAppObjC/AppDelegate.m
  RollbarCommon/Package.swift
  RollbarCommon/Sources/RollbarCommon/DTOs/RollbarDTO.m
  RollbarCommon/Sources/RollbarCommon/include/RollbarDTO.h
  RollbarDeploys/Package.swift
  RollbarNotifier/Package.swift
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarConfig.m
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarLevel.m
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarScrubbingOptions.m
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarTelemetryOptions.m
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarTelemetryType.m
  RollbarNotifier/Sources/RollbarNotifier/Rollbar.m
  RollbarNotifier/Sources/RollbarNotifier/RollbarConfigUtil.m
  RollbarNotifier/Sources/RollbarNotifier/RollbarConfiguration.m
  RollbarNotifier/Sources/RollbarNotifier/RollbarLogger.m
  RollbarNotifier/Sources/RollbarNotifier/RollbarTelemetryOptionsObserver.h
  RollbarNotifier/Sources/RollbarNotifier/RollbarTelemetryOptionsObserver.m
  RollbarNotifier/Sources/RollbarNotifier/include/Rollbar.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarConfig.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarConfigUtil.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarConfiguration.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarLevel.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarLogger.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarScrubbingOptions.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarTelemetry.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarTelemetryOptions.h
  RollbarNotifier/Sources/RollbarNotifier/include/RollbarTelemetryType.h
  RollbarNotifier/Tests/RollbarNotifierTests-ObjC/DTOsTests.m
  RollbarNotifier/Tests/RollbarNotifierTests-ObjC/PayloadTruncationTests.m
  RollbarNotifier/Tests/RollbarNotifierTests-ObjC/RollbarConfigurationTests.m
  RollbarNotifier/Tests/RollbarNotifierTests-ObjC/RollbarTelemetryTests.m
  RollbarNotifier/Tests/RollbarNotifierTests-ObjC/RollbarTests.m
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierConfigUtilTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierConfigurationTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierDTOsTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierLoggerTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierTelemetryTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/RollbarNotifierTruncationTests.swift
  RollbarNotifier/Tests/RollbarNotifierTests/XCTestManifests.swift
Labels: enhancement, v2

#313 chore: set version to 2.0.0-alpha12
  RollbarCommon.podspec
  RollbarDeploys.podspec
  RollbarNotifier.podspec
  RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarConfig.m
  RollbarSDK.podspec
Labels: chore, v2

#315 Create pull_request_template.md
  .github/pull_request_template.md
Labels: chore
