Repository rollbar/rollbar-ios, pull requests merged in 2020-05, with the labels that each got.

#275 Compile without headermap, to fix header file collisions
  Rollbar.podspec
Labels: build, cocoapods, dependencies

#276 release candidate: v1.12.4
  CHANGELOG.md
  Examples/iOSAppWithRollbarCocoaPod/Podfile
  Examples/iOSAppWithRollbarCocoaPod/Podfile.lock
  Examples/iOSAppWithRollbarCocoaPod/iOSAppWithRollbarCocoaPod.xcodeproj/project.pbxproj
  Examples/iOSAppWithRollbarCocoaPod/iOSAppWithRollbarCocoaPod/AppDelegate.m
  Examples/macOSAppWithRollbarCocoaPod/Podfile
  Examples/macOSAppWithRollbarCocoaPod/Podfile.lock
  Examples/macOSAppWithRollbarCocoaPod/macOSAppWithRollbarCocoaPod.xcodeproj/project.pbxproj
  Rollbar.podspec
  Rollbar.xcodeproj/project.pbxproj
  Rollbar/Notifier/RollbarTelemetry.m
  Rollbar/Notifier_DTOs/RollbarConfig.m
  RollbarTests/RollbarTelemetryTests.m
Labels: bug, build, cocoapods

#278 release candidate: v1.12.5
  CHANGELOG.md
  Rollbar.podspec
  Rollbar.xcodeproj/project.pbxproj
  Rollbar/Notifier_DTOs/RollbarConfig.m
Labels: build, cocoapods

#280 release candidate: v1.12.6
  CHANGELOG.md
  Rollbar.podspec
  Rollbar.xcodeproj/project.pbxproj
  Rollbar/Notifier_DTOs/RollbarConfig.m
Labels: build, cocoapods

#281 Set the correct Rollbar.h location in podspec
  Rollbar.podspec
Labels: bug, cocoapods

#282 release candidate: v1.12.7
  CHANGELOG.md
  Examples/iOSAppWithRollbarCocoaPod/Podfile
  Examples/macOSAppWithRollbarCocoaPod/Podfile
  Examples/macOSAppWithRollbarCocoaPod/Podfile.lock
  Rollbar.podspec
  Rollbar.xcodeproj/project.pbxproj
  Rollbar/Notifier_DTOs/RollbarConfig.m
Labels: bug, build, cocoapods

#283 Add RollbarFramework/* to source_files
  Rollbar.podspec
Labels: cocoapods

#284 release candidate: v1.12.8
  CHANGELOG.md
  Rollbar.podspec
  Rollbar.xcodeproj/project.pbxproj
  Rollbar/Notifier_DTOs/RollbarConfig.m
Labels: bug, cocoapods
